create table tbl_produto (id integer generated by default as identity, nome varchar(100), preco float(53) not null, primary key (id));
insert into tbl_produto (nome, preco) values ('Computador',1500.0);
insert into tbl_produto (nome, preco) values ('Mouse',50.0);
insert into tbl_produto (nome, preco) values ('Teclado',100.0);
insert into tbl_produto (nome, preco) values ('Mesa',1000.0);
insert into tbl_produto (nome, preco) values ('Impressora',500.0);
insert into tbl_produto (nome, preco) values ('Monitor',150.0);
insert into tbl_produto (nome, preco) values ('Cadeira',510.0);

